#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#PBS -A fyw-423-ad
#PBS -o outputfile
#PBS -e errorfile
#PBS -V
#PBS -N 1d_random_oxd_test  

#cd /gs/project/fyw-423-aa/hophy/Simulation/1d_serial/1d_serial_kint/1_1_1_1_1_1_1/1dserial_kint
cd /home/hophy/FINAL_CODE/serial/1d/diffusive_oxg_regular
./input0 input0.in
