#!/bin/bash
#PBS -l procs=48
#PBS -l walltime=50:00:00
#PBS -l pmem=1700m
#PBS -A fyw-423-ad
#PBS -o outputfile
#PBS -e errorfile
#PBS -V
#PBS -N 2d_Kinetic_parallel_36000*512
cd /gs/scratch/hophy/Simulation_results/2d_parallel_kint/1_1_1_1_1_1/2dparallel_kint
#cd /home/hophy/FINAL_CODE/parallel/2d/Oxd_model
mpiexec -n 48 ./parallel_input0 parallel_input0.in 
