#!/bin/bash
#PBS -l procs=1
#PBS -l walltime=00:30:00
#PBS -l pmem=1700m
#PBS -A fyw-423-ae
#PBS -o outputfile
#PBS -e errorfile
#PBS -V
#PBS -N 1d_serial_kint  
#cd /gs/scratch/hophy/Simulation_results/2d_serial_kint/1_1_1_1_1/2dserial_kint
cd /home/hophy/FINAL_CODE/serial/2d/Oxd_model
./input0 input0.in

