#!/bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:30:00
#PBS -A fyw-423-ae
#PBS -o outputfile
#PBS -e errorfile
#PBS -V
#PBS -N 1d_serial_kint  
#cd /gs/scratch/hophy/Simulation_results/1d_serial_kint/1_1_1_1_1/1dserial_kint
cd /home/hophy/FINAL_CODE/serial/1d/Kint_Oxd_model
./input0 input0.in

