#!/bin/bash
#PBS -l procs=48
#PBS -l walltime=00:30:00
#PBS -l pmem=1700m
#PBS -A fyw-423-af
#PBS -o outputfile
#PBS -e errorfile
#PBS -V
#PBS -N 1d_Oxidation_parallel_discrete
#cd /gs/project/fyw-423-aa/hophy/Simulation/1d_parallel/1d_parallel_oxd/1_1_1_1_1_1/2dparallel_kint
cd /home/hophy/FINAL_CODE/parallel/1d/Oxd_discrete

mpiexec -n 48 ./parallel_input0 parallel_input0.in 
